/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class im_r_c_java_Main */

#ifndef _Included_im_r_c_java_Main
#define _Included_im_r_c_java_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     im_r_c_java_Main
 * Method:    nativeTestAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL
        Java_im_r_1c_java_Main_nativeTestAll
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
